# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_replacement.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 523)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_check = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_check.setMaximumSize(QtCore.QSize(89, 25))
        self.pushButton_check.setObjectName("pushButton_check")
        self.gridLayout.addWidget(self.pushButton_check, 4, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_frame = QtWidgets.QLabel(self.centralwidget)
        self.label_frame.setObjectName("label_frame")
        self.horizontalLayout_2.addWidget(self.label_frame)
        self.lineEdit_frame = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_frame.setMaximumSize(QtCore.QSize(81, 25))
        self.lineEdit_frame.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_frame.setObjectName("lineEdit_frame")
        self.horizontalLayout_2.addWidget(self.lineEdit_frame)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)
        self.label_heading = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_heading.setFont(font)
        self.label_heading.setAlignment(QtCore.Qt.AlignCenter)
        self.label_heading.setObjectName("label_heading")
        self.gridLayout.addWidget(self.label_heading, 0, 0, 1, 3)
        self.pushButton_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.gridLayout.addWidget(self.pushButton_reset, 4, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_input = QtWidgets.QLabel(self.centralwidget)
        self.label_input.setObjectName("label_input")
        self.horizontalLayout.addWidget(self.label_input)
        self.lineEdit_string = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_string.setObjectName("lineEdit_string")
        self.horizontalLayout.addWidget(self.lineEdit_string)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.textEdit_result = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_result.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(239, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.textEdit_result.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        self.textEdit_result.setFont(font)
        self.textEdit_result.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-top-color: rgb(239, 41, 41);")
        self.textEdit_result.setLineWidth(10)
        self.textEdit_result.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit_result.setObjectName("textEdit_result")
        self.verticalLayout.addWidget(self.textEdit_result)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 22))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLRU = QtWidgets.QAction(MainWindow)
        self.actionLRU.setObjectName("actionLRU")
        self.actionFIFO = QtWidgets.QAction(MainWindow)
        self.actionFIFO.setObjectName("actionFIFO")
        self.actionOptimal_Page_Replacement = QtWidgets.QAction(MainWindow)
        self.actionOptimal_Page_Replacement.setObjectName("actionOptimal_Page_Replacement")
        self.menuMenu.addAction(self.actionLRU)
        self.menuMenu.addAction(self.actionFIFO)
        self.menuMenu.addAction(self.actionOptimal_Page_Replacement)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_string, self.lineEdit_frame)
        MainWindow.setTabOrder(self.lineEdit_frame, self.pushButton_check)
        MainWindow.setTabOrder(self.pushButton_check, self.textEdit_result)
        MainWindow.setTabOrder(self.textEdit_result, self.pushButton_reset)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_check.setText(_translate("MainWindow", "Check"))
        self.label_frame.setText(_translate("MainWindow", "Frame Length:"))
        self.label_heading.setText(_translate("MainWindow", "YOU ARE CALCULATING USING FIFO TECHNIQUE"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset"))
        self.label_input.setText(_translate("MainWindow", "Input String:"))
        self.lineEdit_string.setPlaceholderText(_translate("MainWindow", "1,3,0,3,5,6 or 130356 or 1, 3, 0, 3, 5, 6"))
        self.textEdit_result.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionLRU.setText(_translate("MainWindow", "LRU"))
        self.actionLRU.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionFIFO.setText(_translate("MainWindow", "FIFO"))
        self.actionFIFO.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionOptimal_Page_Replacement.setText(_translate("MainWindow", "Optimal Page Replacement"))
        self.actionOptimal_Page_Replacement.setShortcut(_translate("MainWindow", "Ctrl+O"))
